name: Rust

on:
  push:
    branches: [ "rust" ]
  pull_request:
    branches: [ "rust" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ros-humble

    steps:
    - uses: actions/checkout@v3
    - name: ros2 humble setup
      run: source /opt/ros/humble/setup.bash
    - name: Rustc install
      run: sudo apt install rustc
    - name: Check with Clippy
      run: cargo clippy
    - name: Build
      run: cargo build --all -v
