name: Rust

on:
  push:
    branches: [ "rust" ]
  pull_request:
    branches: [ "rust" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: ros2 humble setup
      run: sudo apt install software-properties-common -y && sudo add-apt-repository universe -y && sudo apt update -y && sudo apt install curl -y && sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null && sudo apt update -y && sudo apt upgrade -y && sudo apt install ros-humble-desktop -y && source /opt/ros/humble/setup.bash
    - name: Check with Clippy
      run: source /opt/ros/humble/setup.bash && cargo clippy
    - name: Build
      run: source /opt/ros/humble/setup.bash && cargo build --all -v
